### ISSUE TITLE
License

### ISSUE THREAD

**Issue by martijn-heil** [robotnikthingy/IronSight#8]
As of now, I could not find any information on this project's license. If you're willing to make this a thriving open source project, I think you need to add a LICENSE file. Under what license are you going to put this?

**Comment by martijn-heil** [comment]
I guess it's automatically GPLv3 licensed due to it's use of the Bukkit API, which is licensed under GPLv3 (not LGPL!)

**Comment by martijn-heil** [comment]
*DISCLAIMER: Obviously I'm not a laywer in any way shape or form.*

As discussed on Discord with robotnikthingy and by the LICENSE file that was added, [IronSight is now GPLv2](https://github.com/robotnikthingy/IronSight/commit/197146e82c3e2a486b4458213ec6aa13c004d068).
Please note that [Bukkit however is GPLv3](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/LICENCE.txt), and that [these licenses are not actually compatible](https://www.gnu.org/licenses/gpl-faq.en.html#v2v3Compatibility).
The question for whether this is even valid at all, then depends on the (to my knowledge) unanswered legal question of whether dynamically linking with Java API's in this plugin manner creates a deriviative work.

The Free Software Foundation's position on this is that yes it does, as illustrated by [their GPL FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#GPLPlugins)

Now I'm really starting to feel like I'm being an annoyance, I dont want to be, but I think this is a crucial  thing to get right, especially in a project that aims to be the open source replacement of CrackShot

**Comment by robotnikthingy** [comment]
No worries, Im no expert in licenses so if I did it wrong I would prefer someone pointed it out. I updated it to GPLv3 so it should be good now

**Comment by martijn-heil** [comment]
Thanks :)
